services:
  automata:
    build: .
    container_name: automata

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

        reservations:
          cpus: '0.1'
          memory: 256M

    healthcheck:
      retries: 10
      timeout: 10s
      interval: 30s
      test: ["CMD", "wget", "--spider", "--quiet", "http://localhost:5678/healthz"]

    ports:
      - "5678:5678"

    volumes:
      - automata:/home/node/.n8n

    environment:
      - TZ=Europe/Rome
      - N8N_RUNNERS_ENABLED=true
      - GENERIC_TIMEZONE=Europe/Rome
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

volumes:
  automata:
    external: true
