services:
  n8n:
    build: .
    container_name: automata

    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

        reservations:
          cpus: '0.1'
          memory: 256M

    ports:
      - "5678:5678"

    volumes:
      - n8n:/home/node/.n8n

    environment:
      - TZ=Europe/Rome
      - N8N_RUNNERS_ENABLED=true
      - GENERIC_TIMEZONE=Europe/Rome
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

volumes:
  n8n:
    external: true
